<?php

declare(strict_types=1);

namespace App\Services\Order\Api\certum;

class Errors
{
    /**
     * 状态描述数组
     */
    protected array $textsStatus = [
        1 => 'Error occurred during processing',
        2 => 'Authentication data in requestHeader/authToken element are incorrect.',
    ];

    /**
     * 错误描述数组
     */
    protected array $textsError = [
        1000 => 'CSR 密钥长度太短',
        1001 => 'CSR 中的公钥算法不受支持',
        1002 => '找不到或空的元素 orderParameters/CSR',
        1006 => '产品代码元素包含已停产的产品代码',
        1007 => '找不到元素 quickOrder/SANEntries',
        1008 => '元素 quickOrder/SANEntries/SANEntry/DNSName 中的域名错误',
        1009 => '找不到元素 quickOrder/requestorInfo',
        1010 => '找不到元素 quickOrder/orderParameters',
        1011 => '找不到元素 quickOrder/orderParameters/orderId',
        1012 => '订单 ID 已被占用',
        1013 => '订单 ID 错误',
        1014 => '找不到元素 quickOrder/orderParameters/productCode',
        1015 => '找不到 CommonName 属性',
        1016 => '找不到 Organization 属性',
        1019 => '找不到 CSR-a 中的 State 属性',
        1020 => '找不到 Country 属性',
        1021 => '找不到 EmailAddress 属性',
        1022 => '电子邮件地址有误',
        1023 => 'orderParameters/customer 元素的值不能与 requestHeader/authToken/username 元素相同',
        1024 => 'CommonName 属性必须编码为 UTF8String',
        1025 => 'EmailAddress 属性必须编码为 IA5String',
        1026 => 'Country 属性必须编码为 PrintableString',
        1027 => 'State 属性必须编码为 UTF8String',
        1028 => 'Locality 属性必须编码为 UTF8String',
        1029 => 'OrganizationUnit 属性必须编码为 UTF8String',
        1030 => 'Organization 属性必须编码为 UTF8String',
        1031 => 'CommonName 属性必须编码为 PrintableString',
        1032 => 'CSR 中的公钥已被使用',
        1033 => '订单 ID 不存在',
        1037 => '元素 approverEmail 中的电子邮件地址有误',
        1038 => '找不到元素 quickOrder/approvers/Approver/approverEmail',
        1040 => '找不到元素 quickOrder/approvers/Approver/approverMethod',
        1042 => '不支持域名验证方法',
        1043 => '订单 ID 包含不允许的字符：“&\'<>',
        1044 => '证书日期为“过去的日期”',
        1045 => 'CommonName 中的域名不在 SANEntries 中',
        1046 => 'SANEntries 元素中只有一个域名可以包含 "*"',
        1048 => '找不到或不正确的元素 taxIdentificationNumber',
        1049 => '无法从 CSR 中读取公钥',
        1053 => '找不到元素 requestorInfo/email',
        1054 => '找不到元素 requestorInfo/firstName',
        1055 => '找不到元素 requestorInfo/lastName',
        1059 => '找不到 Country 属性',
        1060 => 'requestorInfo/email 元素中的电子邮件地址不正确',
        1063 => 'CSR 中的公钥已被列入黑名单',
        1065 => 'requestorInfo/lastName 元素的值超过 255 个字符',
        1066 => 'requestorInfo/phone 元素的值超过 32 个字符',
        1069 => 'shortenedValidityPeriod 元素中提供的证书有效期超过了请求产品的证书有效期',
        1070 => '找不到元素 organizationInfo/validityPeriod/notBefore',
        1071 => '找不到元素 organizationInfo/validityPeriod/notAfter',
        1072 => 'requestorInfo/firstName 元素的值超过 255 个字符',
        1075 => '合作伙伴不允许订购此产品',
        1076 => '找不到或空的元素 customer',
        1077 => 'customer 元素的值超过 64 个字符',
        1078 => 'orderParameters/CSR 元素中的 CSR 不正确',
        1079 => 'orderId 元素的值超过 50 个字符',
        1080 => 'productCode 元素的值超过 3 个字符',
        1081 => 'requestorInfo/email 元素的值超过 255 个字符',
        1083 => 'taxIdentificationNumber 元素的值超过 32 个字符',
        1084 => 'requestHeader/authToken/userName 元素的值超过 255 个字符',
        1085 => 'SANEntries/SANEntry/DNSName 元素中的值超过了允许的字符数',
        1087 => 'approverEmail 元素的值超过 255 个字符',
        1088 => 'orderParameters/language 元素的值超过 2 个字符',
        1089 => 'orderParameters/userAgent 元素的值超过 255 个字符',
        1090 => 'requestHeader/authToken/password 元素的值超过 255 个字符',
        1092 => '找不到 JoISoPN 属性',
        1093 => '找不到 JoISoCN 属性',
        1094 => '找不到 JoILN 属性',
        1095 => '找不到 SerialNumber 属性',
        1096 => 'JoISoCN 属性超过 2 个字符',
        1097 => 'JoISoPN 属性超过 128 个字符',
        1098 => 'JoILN 属性超过 128 个字符',
        1099 => 'JoISoCN 属性包含不支持的国家代码',
        1100 => 'SerialNumber 属性超过 64 个字符',
        1101 => 'CommonName 属性超过 64 个字符',
        1102 => 'Organization 属性超过 255 个字符',
        1103 => 'OrganizationalUnit 属性超过 64 个字符',
        1104 => 'Locality 属性超过 128 个字符',
        1105 => 'State 属性超过 128 个字符',
        1106 => 'EmailAddress 属性超过 255 个字符',
        1107 => 'SANEntries 元素中的域名数量超过了产品允许的值',
        1108 => 'approverEmailPrefix 中的值与前缀列表不匹配',
        1109 => 'orderParameters/validityPeriod/notBefore 元素中的值大于 orderParameters/validityPeriod/notAfter 元素中的值',
        1110 => 'fromDate 中的日期不正确',
        1111 => 'toDate 中的日期不正确',
        1113 => '订单处理中，请稍后再试。如果问题仍然存在，请联系技术支持 (订单状态阻止发送电子邮件验证。订单正在处理或已取消。证书正在签发或已签发。验证电子邮件尚未发送)',
        1114 => '所有验证消息仍然有效。验证电子邮件尚未发送',
        1115 => 'SANEntries/SANEntry/DNSName 元素包含不允许用于所选产品的通配符域名',
        1116 => 'CommonName 包含不允许用于所选产品的通配符域名',
        1117 => 'CommonName 不包含通配符域名，而所选产品要求通配符域名',
        1118 => 'SANEntries/SANEntry/DNSName 元素不包含通配符域名，而所选产品要求通配符域名',
        1119 => 'CSR 中的国家属性包含不允许用于自动签发订单的值',
        1120 => 'CSR 中的组织属性包含不允许用于自动签发订单的值',
        1121 => 'CSR 中的组织单位属性包含不允许用于自动签发订单的值',
        1122 => 'CSR 中的地方属性包含不允许用于自动签发订单的值',
        1123 => 'CSR 中的州属性包含不允许用于自动签发订单的值',
        1124 => 'CSR 中的 CommonName 属性包含不允许用于自动签发订单的值',
        1125 => 'CSR 中的 EmailAddress 属性包含不允许用于自动签发订单的值',
        1126 => 'SerialNumber 属性必须编码为 UTF8String',
        1127 => 'JoILN 属性必须编码为 UTF8String',
        1128 => 'JoISoCN 属性必须编码为 PrintableString',
        1129 => 'JoISoPN 属性必须编码为 UTF8String',
        1131 => '找不到元素 revokeCertificate/RevokeCertificateParameters',
        1132 => '找不到元素 revokeCertificate/RevokeCertificateParameters/serialNumber',
        1133 => '在给定的序列号下找不到证书',
        1134 => 'revokeCertificate/RevokeCertificateParameters/serialNumber 元素中的值超过 64 个字符',
        1135 => 'revokeCertificate/RevokeCertificateParameters/revocationReason 中的值不正确',
        1136 => '此订单有一个有效或即将有效的证书。要取消订单，请先吊销证书',
        1137 => '此订单的证书已过期。无法取消订单',
        1138 => '请求无法继续处理。请联系技术支持',
        1139 => '由于订单状态，无法取消订单。请稍后再试。如果问题仍然存在，请联系技术支持',
        1140 => 'keyCompromitationDate 元素中的日期必须为 YYYY-MM-DD',
        1141 => 'keyCompromitationDate 元素中的日期必须在证书有效日期与当前日期之间',
        1142 => 'revokeCertificate/RevokeCertificateParameters/note 元素中的值超过 250 个字符',
        1143 => '无法吊销证书，因为证书正在吊销过程中',
        1144 => '无法吊销证书，因为证书已过期',
        1145 => '无法吊销证书，因为证书已被吊销',
        1146 => 'revokeCertificate/RevokeCertificateParameters/serialNumber 元素必须为十六进制',
        1147 => '找不到 SANEntries/SANEntry/DNSName 元素的 approvers/Approver 元素',
        1148 => '无法使用私有 IP 地址下订单',
        1150 => 'CSR 中的密钥长度太长',
        1151 => '订单已取消',
        1152 => '找不到元素 quickOrder/approvers/Approver/approverMethod',
        1153 => '页码必须在 [1 - 100] 范围内',
        1154 => '查询返回的记录太多',
        1155 => '找不到页面',
        1156 => 'orderParameters 中的 customer 字段包含不允许的字符：“&\'<>',
        1157 => 'quickOrder/SANEntries/SANEntry/DNSName 元素包含 gTLD',
        1159 => '找不到证书',
        1160 => '证书序列号丢失',
        1161 => '序列号超过 64 个字符',
        1162 => '缺少必要参数（序列号或订单标识符）',
        1163 => '请求中包含不能同时出现的参数（证书序列号和订单标识符）',
        1164 => '无法正确识别证书。请提供证书序列号或 PEM 格式的证书',
        1165 => '证书格式不正确（证书应为 PEM 格式）',
        1166 => '提供的产品代码不能用作续订代码',
        1167 => '原始证书的配置文件与续订配置文件不匹配',
        1168 => 'CN 不匹配',
        1169 => 'Customer 不匹配',
        1170 => '证书由不同的帐户签发',
        1172 => '请求包含附加元素。请根据文档验证请求',
        1173 => '提供的数据与已提供的数据相同。请使用 sendNotification 再次发送验证电子邮件',
        1176 => '订单处理中，请稍后再试。如果问题仍然存在，请联系技术支持 (订单状态阻止发送域验证。订单正在处理或已取消。证书已签发。无法完成必要的操作)',
        1181 => '产品代码错误，无法颁发证书',
        1182 => '找不到 Code 元素',
        1183 => 'verifyDomain/code 元素中的值超过 255 个字符',
        1184 => '验证码已过期',
        1185 => '域名验证错误，请稍后再试',
        1186 => '验证码错误',
        1191 => '有效期超过了所选产品的最大有效期',
        1194 => 'orderSNICertificate/orderSNIParameters/CSR 元素未找到或为空',
        1195 => 'orderSNICertificate/orderSNIParameters/CSR 元素不包含正确的 CSR',
        1196 => 'orderSNICertificate/orderSNIParameters/language 元素的值超过 2 个字符',
        1197 => '找不到元素 orderSNICertificate/orderSNIParameters',
        1198 => '找不到元素 orderSNICertificate/serialNumbers',
        1199 => '至少需要一个 orderSNICertificate/serialNumbers/serialNumber 元素',
        2000 => 'orderSNICertificate/serialNumbers/serialNumber 不能为空',
        2001 => 'orderSNICertificate/serialNumbers/serialNumber 元素中的值超过 64 个字符',
        2002 => 'orderSNICertificate/serialNumbers/serialNumber 元素必须为十六进制格式',
        2003 => '给定的证书已过期或已被吊销',
        2004 => '一个 SNI 证书不能包含另一个 SNI 证书',
        2005 => '提供的证书中没有包含域名',
        2006 => '找不到元素 orderSNICertificate/requestorInfo',
        2010 => '找不到元素 orderSNICertificate/requestorInfo/email',
        2011 => '找不到元素 orderSNICertificate/requestorInfo/firstName',
        2012 => '找不到元素 orderSNICertificate/requestorInfo/lastName',
        2013 => '找不到元素 orderSNICertificate/requestorInfo/phone',
        2016 => 'orderSNICertificate/requestorInfo/email 元素中的电子邮件地址不正确',
        2020 => 'orderSNICertificate/requestorInfo/lastName 元素的值超过 255 个字符',
        2021 => 'orderSNICertificate/requestorInfo/phone 元素的值超过 255 个字符',
        2024 => 'orderSNICertificate/requestorInfo/firstName 元素的值超过 255 个字符',
        2025 => '要订购 SNI 证书，请使用 orderSNICertificate 或 modifySNICertificate 方法',
        2026 => 'orderSNICertificate/requestorInfo/email 元素的值超过 255 个字符',
        2027 => '至少需要一个 modifySNICertificate/serialNumber 或 modifySNICertificate/X509Cert 元素',
        2028 => 'modifySNICertificate/serialNumber 元素不能为空',
        2029 => 'modifySNICertificate/serialNumber 元素中的值超过 64 个字符',
        2030 => 'modifySNICertificate/serialNumber 元素必须为十六进制格式',
        2031 => 'modifySNICertificate/serialNumber 元素中提供的序列号下没有证书',
        2032 => '只能修改 SNI 证书',
        2033 => 'modifySNICertificate/X509Cert 元素中的证书格式不正确',
        2034 => 'modifySNICertificate/X509Cert 元素中缺少证书',
        2035 => '至少需要一个 modifySNICertificate/addSerialNumbers/serialNumber 属性',
        2036 => 'modifySNICertificate/addSerialNumbers/serialNumber 不能为空',
        2037 => 'modifySNICertificate/addSerialNumbers/serialNumber 元素中的值超过 64 个字符',
        2038 => 'modifySNICertificate/addSerialNumbers/serialNumber 必须为十六进制格式',
        2039 => '至少需要一个 modifySNICertificate/removeSerialNumbers/serialNumber 属性',
        2040 => 'modifySNICertificate/removeSerialNumbers/serialNumber 不能为空',
        2041 => 'modifySNICertificate/removeSerialNumbers/serialNumber 元素中的值超过 64 个字符',
        2042 => 'modifySNICertificate/removeSerialNumbers/serialNumber 必须为十六进制格式',
        2043 => '无法同时添加和移除相同的证书',
        2044 => '无法添加证书。未找到证书',
        2045 => '无法将 SNI 证书作为另一个 SNI 证书的一部分',
        2046 => '无法添加已是 SNI 证书一部分的证书',
        2047 => '无法移除不属于 SNI 证书的证书',
        2048 => '结果证书不包含任何域名',
        2049 => 'verifyOrderParameters/note 未找到或为空',
        2050 => 'verifyOrderParameters/note 元素的值超过 227 个字符',
        2051 => 'CommonName 字段中的值不正确',
        2052 => 'getExpiringCertificates/validityDaysLeft 元素未找到或值不正确',
        2053 => 'cancelParameters 元素未找到',
        2054 => '找不到 changeApprovers/Approver 元素',
        2055 => '找不到 orderID 元素',
        2056 => '订单状态不允许添加注释',
        2057 => 'toDate 元素中的值不能早于 fromDate 元素中的值',
        2058 => '找不到 Locality 或 StateOfProvince 属性',
        2059 => 'verificationNotificationEnabled 元素中的值不正确',
        2061 => 'renewCertificate/approvers/verificationNotificationEnabled 元素中的值不正确',
        2063 => '找不到 verifyOrder/verifyOrderParameters/documents/document 元素',
        2064 => '找不到 verifyOrder/verifyOrderParameters/documents/document/type 元素',
        2065 => '找不到 verifyOrder/verifyOrderParameters/documents/document/description 元素',
        2066 => '找不到 verifyOrder/verifyOrderParameters/documents/document/files 元素',
        2067 => '找不到 verifyOrder/verifyOrderParameters/documents/document/files/file 元素',
        2068 => '找不到 verifyOrder/verifyOrderParameters/documents/document/files/file/filename 元素',
        2069 => '找不到 verifyOrder/verifyOrderParameters/documents/document/files/file/content 元素',
        2070 => 'verifyOrder/verifyOrderParameters/documents/document/files/file/content 元素应为 base64 格式',
        2080 => '请求的大小限制已被超出',
        2081 => 'fileName 元素不能包含以下字符：\\ / : * ? " < > |',
        2082 => 'fileName 元素的长度不正确。允许的长度为 3 到 255 个字符',
        2083 => '文档类型不正确',
        2085 => 'verifyOrder/verifyOrderParameters/documents/document/files/file 元素中的某个文件超出了允许的大小限制（30MB）',
        2088 => 'SANEntries/SANEntry/DNSName 元素中的域名部分超过了允许的字符数',
        2089 => '算法未配置',
        2090 => 'hashAlgorithm 元素中有无效值',
        2091 => 'getProductList/HashAlgorithm 元素中无效值',
        2093 => '证书日期来自过去',
        2094 => '证书不符合重新颁发的条件',
        2095 => 'SANEntries/SANEntry/DNSName 元素不能为空',
        2096 => 'serialNumber 元素必须为十六进制字符串',
        2097 => 'ReissueCertificate/CSR 元素不是有效的 CSR 请求',
        2104 => '密钥妥协日期只能为密钥妥协的取消原因指定',
        2109 => '密钥长度无效',
        2121 => 'quickOrder/organizationInfo/verificationPhoneNumber 元素的值超过了 255 个字符的允许大小',
        2122 => 'SimplySign 产品的重新颁发不可用',
        2124 => '不支持的哈希算法',
        2125 => 'CSR 中的签名不正确',
        2126 => '证书无法重新颁发。无法再次重新颁发相同的证书',
        2127 => 'certificateDetails 元素中的值不正确',
        2128 => 'certificateOrder 元素中的值不正确',
        2129 => 'orderStatus 元素中的值不正确',
        2130 => 'SANEntries/SANEntry/DNSName 元素包含已存在于已颁发证书中的域名',
        2131 => '找不到认证请求',
        2137 => 'businessCategory 元素中的值不正确',
        2138 => '找不到 businessCategory 属性',
        2139 => '找不到 StreetAddress 属性',
        2140 => 'StreetAddress (ST) 属性超过 64 个字符',
        2141 => 'StreetAddress (ST) 属性必须编码为 UTF8String',
        2142 => '找不到 PostalCode 属性',
        2143 => 'PostalCode (P) 属性超过 40 个字符',
        2144 => 'PostalCode (P) 属性必须编码为 PrintableString',
        2153 => '给定号码的订单未通过 API 请求',
        2154 => 'postalCode (P) 元素中的值不正确',
        2155 => 'Jurisdiction of Incorporation State or Province Name (JoISoPN) 元素中的值不正确',
        2156 => 'stateOrProvinceName (SP) 中的值不正确',
        2157 => '找不到 approverMethod 元素',
        2158 => '元素过多。只能使用一个 approverEmail 或 approverEmailPrefix',
        2159 => '找不到必要的 approverEmailPrefix 元素',
        2160 => '找不到必要的 approverEmail 元素',
        2161 => 'VerifyDomain 方法不支持多域名请求',
        2162 => '找不到 SANApprover 元素',
        2163 => '该方法不支持此产品',
        2164 => 'SerialNumber 属性无效',
        2165 => 'Join 属性无效',
        2166 => 'Locality 属性无效',
        2167 => 'OrganizationUnit 属性无效',
        2168 => 'Organization 属性无效',
        2169 => 'StreetAddress 属性无效',
        2170 => 'Description 元素的值超过了 1000 个字符的允许大小',
        2171 => 'IP 地址不支持验证方法',
        2172 => '吊销电子邮件与登录电子邮件相同',
        2173 => 'orderParameters/revocationContactEmail 的值无效',
        2175 => '找不到 UnstructuredName 或 UnstructuredAddress 属性',
        2176 => 'UnstructuredName 和 UnstructuredAddress 属性不能同时设置',
        2177 => 'UnstructuredName 属性不是 PrintableString',
        2178 => 'UnstructuredAddress 属性不是 PrintableString',
        2179 => 'UnstructuredName 属性超过了 64 个字符的允许大小',
        2180 => 'UnstructuredAddress 属性超过了 64 个字符的允许大小',
        2181 => 'UnstructuredName 属性不是有效的域名',
        2182 => 'UnstructuredAddress 属性不是有效的 IP 地址',
        2183 => 'Description 属性不是 UTF8String',
        2184 => 'Description 属性超过了 255 个字符的允许大小',
        2185 => 'shortenedValidityPeriod 或 ValidityPeriod/NotAfter 中的日期来自过去',
        2186 => '所选产品的订单不支持通配符域名的验证方法',
        2187 => '请求中的 ValidityPeriod 字段已弃用。要缩短证书有效期，请使用 shortenedValidityPeriod',
        2188 => '重新颁发请求需要重新验证域名。由于验证方法的法规变更，无法重用现有验证',
        2189 => 'VerifyOrder 上传文件数量超过限制',
        2190 => '撤销原因“数据已更改”不适用于 DV 证书。',
        2191 => '至少两个附件的内容相同。不能将相同的附件添加到同一个订单中。',
        2192 => '您尝试操作的证书包含无效的域名。无法执行该操作，请重新下订单。',
        2193 => 'EV SSL 证书中不允许使用 IP 地址。',
        2194 => '未找到属性 givenName。',
        2195 => '属性 givenName 必须以 UTF8String 编码。',
        2196 => '属性 givenName 超过了 16 个字符。',
        2197 => '属性 givenName 的值无效。',
        2198 => '未找到属性 surname。',
        2199 => '属性 surname 必须以 UTF8String 编码。',
        2200 => '属性 surname 超过了 40 个字符。',
        2201 => '属性 surname 的值无效。',
        2204 => '域名控制权验证正在进行中。验证所需时间取决于域名数量。请检查域名验证状态。',
        2205 => '尝试进行域名验证的次数过多。请稍候，检查验证状态，如有必要再重试。',
    ];

    /**
     * 返回一个描述发生错误的数组
     *
     * 返回的数组是一个包含以下键的数组：code、number 和 text
     * 其中 code 是成功代码，number 是错误编号，text 是错误描述
     *
     * @param  int  $status  状态码
     * @param  object|null  $errors  包含错误的对象，如果没有错误则为 null
     * @return array 返回包含错误描述的数组
     */
    public function getErrorText(int $status, ?object $errors): array
    {
        $texts = [];
        $error = ! is_null($errors) ? (array) $errors->Error : [];

        if (empty($error)) {
            $texts[] = $this->textsStatus[$status] ?? '';
        } elseif (isset($error['errorCode'])) {
            $t = $this->textsError[$error['errorCode']] ?? '';
            $v = empty($error['value']) ? '' : ' ['.$error['value'].']';
            $texts[] = $t.$v;
        } else {
            foreach ($error as $e) {
                $t = $this->textsError[$e->errorCode] ?? '';
                $v = empty($e->value) ? '' : ' ['.$e->value.']';
                $texts[] = $t.$v;
            }
        }

        return $texts;
    }
}
