# 安装页面
location ^~ /install {
    try_files $uri /backend/public/install.php?$query_string;
}

# 安装资源文件
location ^~ /install-assets/ {
    try_files $uri /backend/public$uri;
}

# API后端
location ^~ /api {
    try_files $uri /backend/public/index.php?$query_string;
}

# Callback后端
location ^~ /callback {
    try_files $uri /backend/public/index.php?$query_string;
}

# _ignition后端
location ^~ /_ignition {
    try_files $uri /backend/public/index.php?$query_string;
}

# 管理端前端
location ^~ /admin {
    # 前端单页应用需明确指定 root
    root __PROJECT_ROOT__/frontend;
    index index.html;
    location ~* \.(gif|jpe?g|png|bmp|swf|svg|ico|webp|avif|woff|woff2|pdf|js|css)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        access_log off;
        error_log off;
    }
    try_files $uri $uri/ /admin/index.html;
}

# 用户端前端
location ^~ /user {
    # 前端单页应用需明确指定 root
    root __PROJECT_ROOT__/frontend;
    index index.html;
    location ~* \.(gif|jpe?g|png|bmp|swf|svg|ico|webp|avif|woff|woff2|pdf|js|css)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        access_log off;
        error_log off;
    }
    try_files $uri $uri/ /user/index.html;
}

# Easy端前端
location ^~ /easy {
    # 前端单页应用需明确指定 root
    root __PROJECT_ROOT__/frontend;
    index index.html;
    location ~* \.(gif|jpe?g|png|bmp|swf|svg|ico|webp|avif|woff|woff2|pdf|js|css)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        access_log off;
        error_log off;
    }
    try_files $uri $uri/ /easy/index.html;
}

include __PROJECT_ROOT__/frontend/web/web.conf;